// eslint-disable-next-line import/prefer-default-export
export const GAMES = [
  {
    themeValue: 'Action (set A)',
    src: './img/dance.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'cry',
        wordRu: 'плакать',
        imgUrl: './img/cry.jpg',
        audio: './audio/cry.mp3',
      },
      {
        wordEn: 'dance',
        wordRu: 'танцевать',
        imgUrl: './img/dance.jpg',
        audio: './audio/dance.mp3',
      },
      {
        wordEn: 'dive',
        wordRu: 'нырять',
        imgUrl: './img/dive.jpg',
        audio: './audio/dive.mp3',
      },
      {
        wordEn: 'draw',
        wordRu: 'рисовать',
        imgUrl: './img/draw.jpg',
        audio: './audio/draw.mp3',
      },
      {
        wordEn: 'fish',
        wordRu: 'ловить рыбу',
        imgUrl: './img/fish.jpg',
        audio: './audio/fish.mp3',
      },
      {
        wordEn: 'fly',
        wordRu: 'летать',
        imgUrl: './img/fly.jpg',
        audio: './audio/fly.mp3',
      },
      {
        wordEn: 'hug',
        wordRu: 'обнимать',
        imgUrl: './img/hug.jpg',
        audio: './audio/hug.mp3',
      },
      {
        wordEn: 'jump',
        wordRu: 'прыгать',
        imgUrl: './img/jump.jpg',
        audio: './audio/jump.mp3',
      },
    ],
  },
  {
    themeValue: 'Action (set B)',
    src: './img/swim.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'open',
        wordRu: 'открывать',
        imgUrl: './img/open.jpg',
        audio: './audio/open.mp3',
      },
      {
        wordEn: 'play',
        wordRu: 'играть',
        imgUrl: './img/play.jpg',
        audio: './audio/play.mp3',
      },
      {
        wordEn: 'point',
        wordRu: 'указывать',
        imgUrl: './img/point.jpg',
        audio: './audio/point.mp3',
      },
      {
        wordEn: 'ride',
        wordRu: 'ездить',
        imgUrl: './img/ride.jpg',
        audio: './audio/ride.mp3',
      },
      {
        wordEn: 'run',
        wordRu: 'бегать',
        imgUrl: './img/run.jpg',
        audio: './audio/run.mp3',
      },
      {
        wordEn: 'sing',
        wordRu: 'петь',
        imgUrl: './img/sing.jpg',
        audio: './audio/sing.mp3',
      },
      {
        wordEn: 'skip',
        wordRu: 'пропускать, прыгать',
        imgUrl: './img/skip.jpg',
        audio: './audio/skip.mp3',
      },
      {
        wordEn: 'swim',
        wordRu: 'плавать',
        imgUrl: './img/swim.jpg',
        audio: './audio/swim.mp3',
      },
    ],
  },
  {
    themeValue: 'Action (Set C)',
    src: './img/drop.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'argue',
        wordRu: 'спорить',
        imgUrl: './img/argue.jpg',
        audio: './audio/argue.mp3',
      },
      {
        wordEn: 'build',
        wordRu: 'строить',
        imgUrl: './img/build.jpg',
        audio: './audio/build.mp3',
      },
      {
        wordEn: 'carry',
        wordRu: 'нести',
        imgUrl: './img/carry.jpg',
        audio: './audio/carry.mp3',
      },
      {
        wordEn: 'catch',
        wordRu: 'ловить',
        imgUrl: './img/catch.jpg',
        audio: './audio/catch.mp3',
      },
      {
        wordEn: 'drive',
        wordRu: 'водить машину',
        imgUrl: './img/drive.jpg',
        audio: './audio/drive.mp3',
      },
      {
        wordEn: 'drop',
        wordRu: 'падать',
        imgUrl: './img/drop.jpg',
        audio: './audio/drop.mp3',
      },
      {
        wordEn: 'pull',
        wordRu: 'тянуть',
        imgUrl: './img/pull.jpg',
        audio: './audio/pull.mp3',
      },
      {
        wordEn: 'push',
        wordRu: 'толкать',
        imgUrl: './img/push.jpg',
        audio: './audio/push.mp3',
      },
    ],
  },
  {
    themeValue: 'Adjectives',
    src: './img/friendly.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'big',
        wordRu: 'большой',
        imgUrl: './img/big.jpg',
        audio: './audio/big.mp3',
      },
      {
        wordEn: 'small',
        wordRu: 'маленький',
        imgUrl: './img/small.jpg',
        audio: './audio/small.mp3',
      },
      {
        wordEn: 'fast',
        wordRu: 'быстрый',
        imgUrl: './img/fast.jpg',
        audio: './audio/fast.mp3',
      },
      {
        wordEn: 'slow',
        wordRu: 'медленный',
        imgUrl: './img/slow.jpg',
        audio: './audio/slow.mp3',
      },
      {
        wordEn: 'friendly',
        wordRu: 'дружелюбный',
        imgUrl: './img/friendly.jpg',
        audio: './audio/friendly.mp3',
      },
      {
        wordEn: 'unfriendly',
        wordRu: 'недружелюбный',
        imgUrl: './img/unfriendly.jpg',
        audio: './audio/unfriendly.mp3',
      },
      {
        wordEn: 'young',
        wordRu: 'молодой',
        imgUrl: './img/young.jpg',
        audio: './audio/young.mp3',
      },
      {
        wordEn: 'old',
        wordRu: 'старый',
        imgUrl: './img/old.jpg',
        audio: './audio/old.mp3',
      },
    ],
  },
  {
    themeValue: 'Animal (set A)',
    src: './img/cat.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'cat',
        wordRu: 'кот',
        imgUrl: './img/cat.jpg',
        audio: './audio/cat.mp3',
      },
      {
        wordEn: 'chick',
        wordRu: 'цыплёнок',
        imgUrl: './img/chick.jpg',
        audio: './audio/chick.mp3',
      },
      {
        wordEn: 'chicken',
        wordRu: 'курица',
        imgUrl: './img/chicken.jpg',
        audio: './audio/chicken.mp3',
      },
      {
        wordEn: 'dog',
        wordRu: 'собака',
        imgUrl: './img/dog.jpg',
        audio: './audio/dog.mp3',
      },
      {
        wordEn: 'horse',
        wordRu: 'лошадь',
        imgUrl: './img/horse.jpg',
        audio: './audio/horse.mp3',
      },
      {
        wordEn: 'pig',
        wordRu: 'свинья',
        imgUrl: './img/pig.jpg',
        audio: './audio/pig.mp3',
      },
      {
        wordEn: 'rabbit',
        wordRu: 'кролик',
        imgUrl: './img/rabbit.jpg',
        audio: './audio/rabbit.mp3',
      },
      {
        wordEn: 'sheep',
        wordRu: 'овца',
        imgUrl: './img/sheep.jpg',
        audio: './audio/sheep.mp3',
      },
    ],
  },
  {
    themeValue: 'Animal (set B)',
    src: './img/bird.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'bird',
        wordRu: 'птица',
        imgUrl: './img/bird.jpg',
        audio: './audio/bird.mp3',
      },
      {
        wordEn: 'fish',
        wordRu: 'рыба',
        imgUrl: './img/fish1.jpg',
        audio: './audio/fish.mp3',
      },
      {
        wordEn: 'frog',
        wordRu: 'лягушка',
        imgUrl: './img/frog.jpg',
        audio: './audio/frog.mp3',
      },
      {
        wordEn: 'giraffe',
        wordRu: 'жираф',
        imgUrl: './img/giraffe.jpg',
        audio: './audio/giraffe.mp3',
      },
      {
        wordEn: 'lion',
        wordRu: 'лев',
        imgUrl: './img/lion.jpg',
        audio: './audio/lion.mp3',
      },
      {
        wordEn: 'mouse',
        wordRu: 'мышь',
        imgUrl: './img/mouse.jpg',
        audio: './audio/mouse.mp3',
      },
      {
        wordEn: 'turtle',
        wordRu: 'черепаха',
        imgUrl: './img/turtle.jpg',
        audio: './audio/turtle.mp3',
      },
      {
        wordEn: 'dolphin',
        wordRu: 'дельфин',
        imgUrl: './img/dolphin.jpg',
        audio: './audio/dolphin.mp3',
      },
    ],
  },
  {
    themeValue: 'Clothes',
    src: './img/blouse.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'skirt',
        wordRu: 'юбка',
        imgUrl: './img/skirt.jpg',
        audio: './audio/skirt.mp3',
      },
      {
        wordEn: 'pants',
        wordRu: 'штаны',
        imgUrl: './img/pants.jpg',
        audio: './audio/pants.mp3',
      },
      {
        wordEn: 'blouse',
        wordRu: 'блузка',
        imgUrl: './img/blouse.jpg',
        audio: './audio/blouse.mp3',
      },
      {
        wordEn: 'dress',
        wordRu: 'платье',
        imgUrl: './img/dress.jpg',
        audio: './audio/dress.mp3',
      },
      {
        wordEn: 'boot',
        wordRu: 'ботинок',
        imgUrl: './img/boot.jpg',
        audio: './audio/boot.mp3',
      },
      {
        wordEn: 'shirt',
        wordRu: 'рубашка',
        imgUrl: './img/shirt.jpg',
        audio: './audio/shirt.mp3',
      },
      {
        wordEn: 'coat',
        wordRu: 'пальто',
        imgUrl: './img/coat.jpg',
        audio: './audio/coat.mp3',
      },
      {
        wordEn: 'shoe',
        wordRu: 'туфли',
        imgUrl: './img/shoe.jpg',
        audio: './audio/shoe.mp3',
      },
    ],
  },
  {
    themeValue: 'Emotions',
    src: './img/smile.jpg',
    incorrectSound: './audio/error.mp3',
    correctSound: './audio/correct.mp3',
    winSound: './audio/success.mp3',
    failureSound: './audio/failure.mp3',
    correctStar: './img/starWin.svg',
    incorrectStar: './img/starFailure.svg',
    gameCards: [
      {
        wordEn: 'sad',
        wordRu: 'грустный',
        imgUrl: './img/sad.jpg',
        audio: './audio/sad.mp3',
      },
      {
        wordEn: 'angry',
        wordRu: 'сердитый',
        imgUrl: './img/angry.jpg',
        audio: './audio/angry.mp3',
      },
      {
        wordEn: 'happ',
        wordRu: 'счастливый',
        imgUrl: './img/happy.jpg',
        audio: './audio/cry.mp3',
      },
      {
        wordEn: 'tired',
        wordRu: 'уставший',
        imgUrl: './img/tired.jpg',
        audio: './audio/tired.mp3',
      },
      {
        wordEn: 'surprised',
        wordRu: 'удивлённый',
        imgUrl: './img/surprised.jpg',
        audio: './audio/surprised.mp3',
      },
      {
        wordEn: 'scared',
        wordRu: 'испуганный',
        imgUrl: './img/scared.jpg',
        audio: './audio/scared.mp3',
      },
      {
        wordEn: 'smile',
        wordRu: 'улыбка',
        imgUrl: './img/smile.jpg',
        audio: './audio/smile.mp3',
      },
      {
        wordEn: 'laugh',
        wordRu: 'смех',
        imgUrl: './img/laugh.jpg',
        audio: './audio/laugh.mp3',
      },
    ],

  },
];
